development:
  adapter: postgresql
  encoding: unicode
  database: diploma_development
  pool: 5
  username: anton
  password: rws3Swfas4

test:
  adapter: postgresql
  encoding: unicode
  database: diploma_test
  pool: 5
  username: anton
  password: rws3Swfas4

production:
  adapter: postgresql
  encoding: unicode
  #host: localhost
  #port: 5432
  database: diploma
  pool: 5
  username: anton
  password: rws3Swfas4
